FOLDER="/data"
BLOB_DESTINATIONCONTAINER_URL=$1
BLOB_DESTINATIONKEY=$2
mkdir $FOLDER
echo "Container URL: $BLOB_DESTINATIONCONTAINER_URL"
echo "Container Key: $BLOB_DESTINATIONKEY"
azcopy --source $FOLDER --destination $BLOB_DESTINATIONCONTAINER_URL --dest-key $BLOB_DESTINATIONKEY --recursive --quiet